// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetUser(ctx context.Context, id uuid.UUID) (*Users, error)
	ListUsers(ctx context.Context) ([]*Users, error)
	UpdateName(ctx context.Context, arg *UpdateNameParams) (*Users, error)
}

var _ Querier = (*Queries)(nil)
