// Code generated by "stringer -type Environment"; DO NOT EDIT.

package env

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Local-1]
	_ = x[Testing-2]
	_ = x[Staging-3]
	_ = x[Development-4]
	_ = x[CI-5]
	_ = x[Production-6]
}

const _Environment_name = "LocalTestingStagingDevelopmentCIProduction"

var _Environment_index = [...]uint8{0, 5, 12, 19, 30, 32, 42}

func (i Environment) String() string {
	i -= 1
	if i >= Environment(len(_Environment_index)-1) {
		return "Environment(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Environment_name[_Environment_index[i]:_Environment_index[i+1]]
}
